### ISSUE TITLE
[STYLE] 관객앱 응원톡 신고모달 수정

### ISSUE THREAD

**Issue by HiimKwak** [hufscheer/client_v2#208]
## TODO
- [x] 응원톡 신고메뉴 터치영역이 현재 메뉴아이콘에 한정돼있어 모바일에서 클릭하기 매우 어려운 상황입니다. 이에 응원톡 기록 시간까지 클릭 영역으로 합병해 클릭하기 쉽게 조정하였습니다.
- [x] 응원톡 신고메뉴 모달 내 요소가 현재 10px로 맞춰져있습니다. 응원톡 다른 요소들이 12px로 커진만큼 신고모달도 따라서 키워주었습니다.
- [x] 응원톡 등록시간 + 메뉴 영역에 width: max-content 속성을 추가해 메뉴 아이콘이 숨겨지는 버그를 수정했습니다.
