### ISSUE TITLE
[FEAT] 공통 스타일 색상 개선

### ISSUE THREAD

**Issue by ohprettyhak** [hufscheer/client_v2#301]
## TODO
공통 스타일을 개선합니다.

- [x] 색상을 css-variable로 적용
- [x] 매니저 및 관객 앱에서 공통으로 사용되는 색상 분리 
- [x] 폰트 적용 방식 개선
